// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon's pooled connection (DATABASE_URL) doesn't support the session-level
    // features the migration engine needs — use the unpooled one here instead.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
